name: CI/CD - Cidades ESGInteligentes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  PROJECT_DIR: Projeto-ESG-Integrado

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B clean package -DskipTests

      - name: Run tests
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B test

      - name: Save JAR name
        working-directory: ${{ env.PROJECT_DIR }}
        run: echo "APP_JAR=$(ls target/*.jar | head -n 1)" >> $GITHUB_ENV

  docker_build_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ vars.REGISTRY }}
      APP_NAME: ${{ vars.APP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PROJECT_DIR }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest

      - name: Save tag artifact
        run: echo "${{ github.sha }}" > image_tag.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

  deploy_azure:
    needs: docker_build_push
    runs-
