name: CI/CD - Cidades ESGInteligentes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write   # necessário para o login no Azure via OIDC (v2)

env:
  PROJECT_DIR: Projeto-ESG-Integrado
  REGISTRY_HOST: ghcr.io
  REGISTRY_NAMESPACE: ${{ github.repository_owner }}
  APP_NAME: cidades-esginteligentes   # valor fixo (ou use vars.APP_NAME se já criou no GitHub)

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B clean package -DskipTests

      - name: Run tests
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B test

      - name: Save JAR name
        working-directory: ${{ env.PROJECT_DIR }}
        run: echo "APP_JAR=$(ls target/*.jar | head -n 1)" >> $GITHUB_ENV

  docker_build_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR (GitHub Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PROJECT_DIR }}
          file: ./${{ env.PROJECT_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}:latest

      - name: Save tag artifact
        run: echo "${{ env.IMAGE_TAG }}" > image_tag.txt

      - uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

  deploy_azure:
    needs: docker_build_push
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTI_
