name: CI/CD - Cidades ESGInteligentes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  PROJECT_DIR: Projeto-ESG-Integrado
  REGISTRY_HOST: ghcr.io
  REGISTRY_NAMESPACE: ${{ toLower(github.repository_owner) }}  # força minúsculas
  APP_NAME: cidades-esginteligentes

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B clean package -DskipTests

      - name: Run tests
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B test

      - name: Save JAR name (opcional)
        working-directory: ${{ env.PROJECT_DIR }}
        run: echo "APP_JAR=$(ls target/*.jar | head -n 1)" >> $GITHUB_ENV

  docker_build_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PROJECT_DIR }}
          file: ./${{ env.PROJECT_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}:latest

      - name: Save tag artifact
        run: echo "${{ env.IMAGE_TAG }}" > image_tag.txt

      - uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

  deploy_azure:
    needs: docker_build_push
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      REGISTRY_HOST: ghcr.io
      REGISTRY_NAMESPACE: ${{ toLower(github.repository_owner) }}  # força minúsculas aqui também
      APP_NAME: cidades-esginteligentes
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/download-artifact@v4
        with:
          name: image_tag
        path: .

      - name: Read tag
        id: gettag
        run: echo "TAG=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}:${{ steps.gettag.outputs.TAG }}

      - name: Restart app (optional)
        run: az webapp restart -g RG-ESG -n ${{ env.AZURE_WEBAPP_NAME }}
